### ISSUE TITLE
Cannot install from source

### ISSUE THREAD

**Issue by nils-werner** [JelteF/PyLaTeX#70] opened 2015-06-18 09:20 UTC
Installing on Python 2 from source fails with

    $ pip install -e .
    Obtaining file:///Users/me/Projekte/pylatex/PyLaTeX
        Complete output from command python setup.py egg_info:
        running egg_info
        error: error in 'egg_base' option: 'python2_source' does not exist or is not a directory

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /Users/me/Projekte/pylatex/PyLaTeX

**Comment by JelteF** [comment] 2015-06-18 11:37
This is correct. The source for Python 2 is not stored in the repository. You can create it by running convert_to_py2.sh

You do need 3to2 for this.

**Comment by JelteF** [comment] 2015-06-18 11:50
I will close this issue since it is by design. The autogenerated code should not be in the repository.

**Closed** 2015-06-18 11:51 UTC
